name: Slither

on:
  push:
    branches: [ master ]
    paths:
      - "contracts/**"
      - ".github/workflows/slither.yaml"
  pull_request:
    branches: [ master ]
    paths:
      - "contracts/**"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Setup
        run: |
          yarn
          sudo add-apt-repository ppa:ethereum/ethereum
          sudo apt-get update
          sudo apt-get install solc
          pip3 install slither-analyzer
      - name: Run Slither
        id: slither
        run: echo "::set-output name=output::$(slither .)"
      - name: Create commit comment
        uses: peter-evans/commit-comment@v1
        with:
          body: ${{steps.slither.outputs.output}}
