name: Slither

on:
  push:
    branches: [ master ]
    paths:
      - "contracts/**"
      - ".github/workflows/audit.yaml"
  pull_request:
    branches: [ master ]
    paths:
      - "contracts/**"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Setup
        run: |
          yarn
          sudo add-apt-repository ppa:ethereum/ethereum
          sudo apt-get update
          sudo apt-get install solc
          pip3 install slither-analyzer
      - name: Run Slither
        id: slither
        continue-on-error: true
        run: slither . > output.txt 2>&1
      - name: Get error comment body
        id: get-comment-body-error
        run: |
          body=$(cat output.txt)
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}" 
          echo ::set-output name=body::$body
      - name: Create commit comment
        uses: peter-evans/commit-comment@v1
        with:
          body: |
            ```
            ${{ steps.get-comment-body-error.outputs.body }}
            ```
