name: Slither

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: trailofbits/slither:latest

    steps:
    - uses: actions/checkout@v2
    - run: "solc **/*.sol"
